name: thansira_travels
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  carousel_slider: ^5.0.0
  dots_indicator: ^4.0.1
  http: ^1.1.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/temples/
    - assets/images/social/

  fonts:
    - family: poorStory
      fonts:
        - asset: assets/fonts/PoorStory-Regular.ttf

    - family: urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
